### ISSUE TITLE
对类和解构的需求

### ISSUE THREAD

**Issue by nodyang** [NewLifeX/NewLife.Siemens#1]
有没有可能 跟s7.net 一样 对类
 实现封装和读取。靠点位  如果需求量大 好累的

![image](https://github.com/NewLifeX/NewLife.Siemens/assets/3090191/1f2fe6ac-6404-41f0-8974-780663272a88)

我们的点位 超5000.

**Comment by nnhy** [comment]
系统有个地方维护点位表，然后驱动层按照点位表分批读取数据
